### ISSUE TITLE
SmartSense Open/Closed Sensor, SmartSense Moisture, Simulated Switch (and other many other DTHs) is missing standard Capability "sensor" and/or "actuator"

### ISSUE THREAD

**Issue by CosmicPuppy** [SmartThingsCommunity/SmartThingsPublic#1058]
### All DTHs should claim `capability "sensor"` and/or `capability "actuator"`.

_For reference,_ the **SmartSense _Motion_ Sensor** correctly claims `capability "sensor"` here:
https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/2b3a4e1278fbf2838621cf6a419cbbde9d37224c/devicetypes/smartthings/smartsense-motion-temp-sensor.src/smartsense-motion-temp-sensor.groovy#L26

But the **SmartSense _Open/Closed_ Sensor** does not:
https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/2b3a4e1278fbf2838621cf6a419cbbde9d37224c/devicetypes/smartthings/smartsense-open-closed-sensor.src/smartsense-open-closed-sensor.groovy#L21

---

This is critical to **SmartTiles V6** because we encourage the users to select _all_ their devices with two general filter input statements (sensor and actuator). As such, Devices of this DTH are currently not selectable in our SmartApp: **SmartTiles V6 Beta (Connect)**.

**Comment by CosmicPuppy** [comment]
`Capability "sensor"` is _**also**_ missing in:  https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/tile-ux/tile-basic-presence.src/tile-basic-presence.groovy#L20

**Comment by CosmicPuppy** [comment]
**And on SmartSense Moisture Sensor:**
https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/2b3a4e1278fbf2838621cf6a419cbbde9d37224c/devicetypes/smartthings/smartsense-moisture-sensor.src/smartsense-moisture-sensor.groovy#L18

**Comment by workingmonk** [comment]
closing this issue as you've open the PRs to fix the issue
