### ISSUE TITLE
SmartThings MultiSensor 6

### ISSUE THREAD

**Issue by jvmahon** [SmartThingsCommunity/SmartThingsPublic#1069]
The published device handler for the Aeon Labs Multisensor 6 has a serious error which prevents proper installation of the Multisensor 6. Specifically, the device handler fingerprint is incorrect.

 As published, the fingerprint lists an outClusters "0x5A", but the "0x5A" needs to be part of the inclusters, and there should be no outClusters for this device.

Fingerprint should read:

fingerprint deviceId: "0x2101", inClusters: "0x5E,0x86,0x72,0x59,0x85,0x73,0x71,0x84,0x80,0x30,0x31,0x70,0x7A,0x5A"

**Comment by workingmonk** [comment]
@dkirker @tylerlange @mckeed

**Comment by tylerlange** [comment]
@dkirker i think you were working on this, correct?

**Comment by dkirker** [comment]
@tylerlange @workingmonk @mckeed Yup! I am working on a PR to fix this and another bug. :) Should come today or tomorrow.

**Comment by jvmahon** [comment]
Thanks!

**Comment by dkirker** [comment]
Expected to be deployed on 8/2-8/3.

**Comment by workingmonk** [comment]
closing the issue as the code has been deployed
