### ISSUE TITLE
ruby with SmartThings

### ISSUE THREAD

**Issue by tsaohucn** [SmartThingsCommunity/SmartThingsPublic#1120]
I use the computer language "ruby" , is there any resources about ruby of SmartThings and how can i use "SmartThings API" by ruby , I don't know if it can work?

**Comment by workingmonk** [comment]
please use the resources at [Community Site](https://community.smartthings.com/) and [Docs](http://docs.smartthings.com/en/latest/) to learn more about how to use the API key.

Closing this issue as it is not an issue with the code.
