### ISSUE TITLE
Support for Osram Smart+ Classic E27 Multicolor (OSRAM/LEDVANCE CLA60 RGBW Z3)

### ISSUE THREAD

**Issue by m1kegibson** [SmartThingsCommunity/SmartThingsPublic#11281]
Bulbs boxed as Osram Smart+ Classic E27 Multicolor, however, when pairing with Zigbee have manufacturer LEDVANCE and model CLA60 RGBW Z3. As a consequnce not recognised for what they are by Smrtthings and show up as Things.

I added the following fingerprint to ZLL RGBW Bulb and published locally and the bulbs are now recognised.  Could this be added to main branch.

However, in the raw description there is a cluster 0B05 which appears out of place when compared with other Osram RGBW bulbs.  I am not sure whether this cluster should be incorporated in fingerprint.

fingerprint profileId: "C05E", inClusters: "0000,0003,0004,0005,0006,0008,0300,0B05,1000,FC0F", outClusters: "0019", "manufacturer":"LEDVANCE", "model":"CLA60 RGBW Z3", deviceJoinName:"OSRAM/LEDVANCE CLA60 RGBW Z3"

**Comment by tpmanley** [comment]
@m1kegibson thanks for the report. I just put up a PR that should allow this device and similar ones to join using the correct DTH even though we don't have a fingerprint with the exact manufacturer and model. We're also going to talk to Osram about certifying these devices at which time we'd add the manufacturer/model fingerprint.

https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/11289
