### ISSUE TITLE
SONOS unable to parse new phrases for TTS

### ISSUE THREAD

**Issue by ashutosh1982** [SmartThingsCommunity/SmartThingsPublic#123]
This issue started about a month back and seems like ST is aware but has it at a low priority.

**Comment by tylerlange** [comment]
Hi @ashutosh1982! Per my previous comment, this tool is specifically for issues related to code on our GitHub repo. If you see an issue, please report it. In the mean time other issues, such as those related to our platform or our mobile app, should be reported through support@smartthings.com.

We're aware of the issue parsing TTS messages and hope to have it corrected shortly.
