### ISSUE TITLE
Mode Misfires

### ISSUE THREAD

**Issue by ashutosh1982** [SmartThingsCommunity/SmartThingsPublic#124]
Since their last platform upgrade, ST has been having a lot of issues with mode based triggers. The SmartAlarm app for example would trigger alarm even though the mode is set to Home - Within the app the state would show as Alarm. Also noticed this on the drop cam app that would take pics only in away mode.

**Comment by tylerlange** [comment]
Hi @ashutosh1982! Thanks for creating an issue. This tool is specifically for creating issues related to our SmartThingsPublic repo. We understand that there's a known issue related to mode filtering. Our engineers are investigating. In the mean time please continue to contact support@smartthings.com if you see this issue.
