### ISSUE TITLE
Error viewing camera

### ISSUE THREAD

**Issue by josserman** [SmartThingsCommunity/SmartThingsPublic#1265]
First off, HUGE thank you for creating this! I'm a new Smartthings user, and very excited to learn how to use the custom development and from such an incredibly well built/documented program! Can't wait to start integrating this all together!

So I'm having an issue under cameras where I can turn streaming on/off, but can't see the video. I'm getting the message attached.

![img_5778](https://cloud.githubusercontent.com/assets/22265899/18611953/d72f34ec-7d18-11e6-8163-14ac7f3f3459.jpg)

Thank you!
Justin

**Comment by workingmonk** [comment]
@josserman Nest is not officially supported as of right now. Our community devs might have the solution that you are looking for at [community.smartthings.com](https://community.smartthings.com)
