### ISSUE TITLE
 Change your device's icons isn't working  right.

### ISSUE THREAD

**Issue by dfairbro1** [SmartThingsCommunity/SmartThingsPublic#127]
From Support Sept 14th

Roger (SmartThings)
Sep 14, 3:31 AM

Hey Dawn,

At the moment, the ability to change your device's icons isn't working quite right. We are aware of this and are working hard on getting this fixed.

**Comment by tylerlange** [comment]
Hi Dawn,

Thanks for posting! This tool is specifically for posting and discussing issues with the code in our SmartThingsPublic repo. It's my understanding that the issue you're describing is unrelated to the code hosted here. If you can point out a specific issue please let me know!

Thanks!

**Comment by dfairbro1** [comment]
Tyler
Thanks for the info. I was to understand it was a place to put known issues. Below is the copy of the response from your team regarding the known issue of icons not being able to be changed.
Sep 14, 3:31 AM 

Hey Dawn,

At the moment, the ability to change your device's icons isn't working quite right. We are aware of this and are working hard on getting this fixed.

I just checked and could not find the Smart WeatherStation, either. Apparently it hasn't been added. I'll see if I can find out and let you know

In the meantime, if you have any other questions or concerns, please let me know.

Cheers,

\Roger\
SmartThings Support

Dfairbro1
Sep 12, 1:47 PM 

Good morning folks,
Just finished my migration to the V2 hub. Went mostly well ( about 98%). Have a few quirks that I need your help with. Looks like I cannot update icons. It picks the icon doesn't save it. I'm trying to kick recess lighting icon for my lights.
Another small things I can't seem to find the smart WeatherStation tile . Did that get removed? It used to be under conveniences, I can't seem to find it now. If it did,are there any alternatives. 

I think that's the worst of my problems for now (not too bad). 

Sent from my iPad
Dawn Fairbrother

**Comment by Dianoga** [comment]
@tylerlange A movement has started within the community to use this issue tracker as a place to keep track of known issues. See this post: https://community.smartthings.com/t/list-of-community-known-issues/21468

**Comment by tylerlange** [comment]
Closing as this issue is not related to this repo.
