### ISSUE TITLE
[BUG] HubAction HTTP Response Header Parsing

### ISSUE THREAD

**Issue by mullender** [SmartThingsCommunity/SmartThingsPublic#1368]
After some experimentation I discovered an issue in the way the [HubAction](http://docs.smartthings.com/en/latest/cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/building-the-device-type.html?highlight=hubaction#making-outbound-http-calls-with-hubaction) parses HTTP response headers.

The issue is that the hubaction response parser requires a space `' '` after the colon `':'` that separates the `field-name` from the `field-value`.
The [HTTP Spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) does not require a space, (but does prefer it). 

> The field value MAY be preceded by any amount of LWS, though a single SP is preferred.

Unfortunately some Hikvision IP camera's send the content length without preceding the value with a space. This makes it impossible to implement the Image.take() capability for these devices.

It would be nice if the hubaction parser could be made to accept response headers with and without space between the colon and the field-value.

**Working Response** Note the space `Content-Length:<SP><length>`

```
HTTP/1.1 200 OK
Content-Type: image/jpeg; charset="UTF-8"
Content-Length: 223556

<data>
```

**Not Working** Note the absence of a space `Content-Length:<length>`

```
HTTP/1.1 200 OK
Content-Type: image/jpeg; charset="UTF-8"
Content-Length:223556

<data>
```

**Comment by workingmonk** [comment]
@lbredeso would require a change in the underlying library?

**Comment by lbredeso** [comment]
@workingmonk @mullender Thanks for the bug report! We believe we have found the underlying issue, and will work on a fix.

**Comment by workingmonk** [comment]
We deployed the fix a few days ago. Closing the issue out. @mullender let us know if you are still seeing the issue.

**Comment by mullender** [comment]
@workingmonk I can confirm the fix is working correctly. I was able to retrieve images from my hikvision camera's.
Thanks for the quick fix!
