### ISSUE TITLE
zigbee-rgbw-bulb hues are off

### ISSUE THREAD

**Issue by joejulian** [SmartThingsCommunity/SmartThingsPublic#1400]
scaledHueValue is calculated by taking a byte dividing by 255 and multiplying by 100. A hue should be between 0 and 360 though. Initial tests with lightify bulbs show that changing the multiplier to 360 produces the correct hues.

**Comment by workingmonk** [comment]
cc @larsfinander @tpmanley 
We made the change for hue to represented as 0-100 to get in line with the docs. If that is causing issues in color reproduction, it might be worth looking at this again

**Comment by joejulian** [comment]
Clearly this isn't a priority for ST so I'm just going to keep running my own custom devices and close this. I hate the nagging reminder every time I look at my open issues and PRs.

**Comment by tpmanley** [comment]
@joejulian I apologize for missing or forgetting about this. As far as I can tell our device type handlers and smartapps do consistently expect hue to be 0-100. Are you aware of a smartapp that is using 0-360 instead of 0-100 or are you just saying that hue really should be 0-360 to give the most accurate color?

**Comment by joejulian** [comment]
It has to be 0-360 or you don't get 2/3rds of the colors.

**Comment by workingmonk** [comment]
the expectation is for smartapps to convert 0-360 from the user input to 0-100 for device handler, which converts it to 0-254 range based on the zigbee spec

**Comment by joejulian** [comment]
That's not what I was observing.

**Comment by tpmanley** [comment]
What Smartapp are you using?

**Comment by joejulian** [comment]
Just an MQTT bridge

**Comment by workingmonk** [comment]
me and @tpmanley found the issue with the hue conversion with that bridge smartapp. if you normalize the value with 100 instead of 360, it should help with the problems that you are seeing

**Comment by joejulian** [comment]
Well it has been a year since I debugged this. I'll try again.
