### ISSUE TITLE
smartpower-dimming-outlet.groovy not showing on/off state

### ISSUE THREAD

**Issue by Xtropy74** [SmartThingsCommunity/SmartThingsPublic#1684]
Since commit 65d4a811b02b03c30c656677d6f0f655c170e13a the smartpower-dimming-outlet.groovy DTH no longer shows on/off states when using "set level" commands. Using C0re (for example) to set the level to 60% results in the light turning on to 60% but the device shows the device is still off. Only On/Off commands result in the DTH properly reflecting the device state.

Looks like this was fixed in other DTH's but not applied to this one: be2e19e4069cd65bfc5317befe943bb4b96a8ff9

Following code needs to be changed?

def setLevel(value) {
	zigbee.setLevel(value)

Needs to be changed to:

def setLevel(value) {
  zigbee.setLevel(value) + zigbee.onOffRefresh() + zigbee.levelRefresh()       //adding refresh because of ZLL bulb not conforming to send-me-a-report

**Comment by workingmonk** [comment]
@varzac This is what your current PR fixes, right?

**Comment by varzac** [comment]
I believe so yes.  However, depending on the device being used it could also possibly be due to changes we made to setLevel a few weeks back.  I would need to see logs, or know the device to be certain.

**Comment by Xtropy74** [comment]
The device is:

manufacturer: CREE
model: Connected A-19 60W Equivalent

Is this being addressed? I had to create my own DTH using a history commit in order for my bulbs to work correctly....

**Comment by workingmonk** [comment]
why was the bulb using the smartpower-dimming-outlet DTH? it should either be using https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/cree-bulb.src/cree-bulb.groovy or https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/zll-dimmer-bulb.src/zll-dimmer-bulb.groovy

**Comment by Xtropy74** [comment]
Short answer in two words: Local processing

Long answer, the Cree bulb does not support local processing and the DTH doesn't work well. Moving the sliders adjusts the brightness but jumps back to where you started. IE: Brightness is at about the 10% mark, you slide to 90%, the bulb brightens but the slider jumps back to 10%. There is also a lot of lag with the on/off function of the Cree or the status is not updated at all. Most users in the forum that have Cree bulbs use the Smartpower DTH because of the buggy Cree DTH and for local processing purposes.

A quick search for "Cree" on the community forums will show pages and pages of threads related to how poorly the Cree DTH performs which is why most of us 'have been" using Smartpower since it 'was' reliable.

**Comment by workingmonk** [comment]
1. I agree with you on the local processing front. The cree DTH is not marked to run locally yet, we are working on a solution that would fix this 'soon'
2. The brightness issue was fixed by Zach about a month ago, we now issue a refresh command along with the setLevel to get the latest values
3. The status can take up to 5 min to be updated if the bulb is actuated outside of the hub, for example using a zigbee remote like Lutron. The reasoning for this is: Cree is NOT a HA bulb, it is a ZLL bulb. It does not follow the HA spec of reporting a change of attribute back to the hub

**Comment by Xtropy74** [comment]
Thanks for the information. I'll revisit the Cree DTH until this one is resolved and/or Cree is processed locally. Do appreciate the transparency and assistance. I'll also play with the other ZLL bulb DTH.

**Comment by varzac** [comment]
Yeah, basically it is the difference between the DTH supporting an HA vs a ZLL device.  They are meant to behave differently and so we treat them differently.  Do let me know if the CREE DTH still has issues though.
