### ISSUE TITLE
Can't stop the music

### ISSUE THREAD

**Issue by maxcredits** [SmartThingsCommunity/SmartThingsPublic#1802]
I implemented this using SmartThings and even after deleting the rule from SmartThings and rebooting the network I still can't stop the Bose from playing. Tried everything.

**Comment by marstorp** [comment]
What did you implement?

**Comment by maxcredits** [comment]
Well, I’m not sure.. :) I installed a smart things app for my Bose based on this script I believe. Anyway, once it was started through a motion sensor I couldn’t figure out how to get it to stop. The music just kept playing. I finally ended up rebooting all of my hubs and router and Bose system to get into quit. It was interesting. 

J

**Comment by workingmonk** [comment]
so has the issue stopped now?

**Comment by maxcredits** [comment]
Yes, after I rebooted everything.. When I get a some time I will try to reproduce it and see what happens.

**Comment by workingmonk** [comment]
cool. i'll close the issue for now. A better place for discussion is our community, where other devs can help and solve the issue faster
