### ISSUE TITLE
Bug (missing command) in ST's Ozom Smart Siren DTH

### ISSUE THREAD

**Issue by jsconstantelos** [SmartThingsCommunity/SmartThingsPublic#19795]
I had an intrusion happen this morning (by accident thankfully), and noticed that STHM didn't trip the siren.  I'm using a Heiman zigbee siren which is using your "Ozom Smart Siren" dth.  I tweaked it to also turn on the strobe, so technically I'm using my own DTH, but still noticed your DTH is missing a key command called "BOTH".

The DTH source code I used is missing that command:

https://raw.githubusercontent.com/SmartThingsCommunity/SmartThingsPublic/a9951cb863820002192e5c6cb43506637a782ebb/devicetypes/smartthings/ozom-smart-siren.src/ozom-smart-siren.groovy

I thought you guys would like to know since this siren will not sound when called from STHM based upon what happened to me this morning.

Here's the custom DTH I'm using based off of yours:

https://raw.githubusercontent.com/jsconstantelos/SmartThings/master/devicetypes/jsconstantelos/my-heiman-smart-siren.src/my-heiman-smart-siren.groovy

**Comment by tpmanley** [comment]
Thanks for the report @jsconstantelos . Here is a PR with the fix: https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/19943
