### ISSUE TITLE
Simulated presence sensor displays incorrect log message

### ISSUE THREAD

**Issue by lymanepp** [SmartThingsCommunity/SmartThingsPublic#2076]
Log messages says 'arrived' when it should say 'departed'

**Comment by lymanepp** [comment]
Pull request has been submitted

**Comment by workingmonk** [comment]
@lymanepp closing the issue as i have merged your PR. 

👍  for creating the PR

https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/2075
