### ISSUE TITLE
Add sunrise/sunset offset

### ISSUE THREAD

**Issue by cdoyle0** [SmartThingsCommunity/SmartThingsPublic#22]
Support an offset in minutes to allow (for example) lights to come on just before sunset.

**Comment by workingmonk** [comment]
Is this what you are looking for:
https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/smartapps/smartthings/sunrise-sunset.src/sunrise-sunset.groovy#L40-L47

**Comment by cdoyle0** [comment]
Sorry, I just opened an issue so I could link to a pull request. The hello-home-phrase-director takes both time and presence into account BUT doesn't let you set an offset. This makes it so the modes change after it's already a bit dark. The plugin you linked is what I based my PR on (although I think there may be a bug in my PR I haven't had a chance to take a look at).
