### ISSUE TITLE
CA3570 - Status reports but cannot control

### ISSUE THREAD

**Issue by Vferretti1998** [SmartThingsCommunity/SmartThingsPublic#2212]
I installed the device handler from LunkwillAndFook without any problems.  I see the handler is associated with the switch.  The switch is set up in Single Switch mode to control a pool pump.  The Primary switch behavior is set to Switch All.  My hub is about 15 feet away from the switch with only a wood frame wall between.  My Smartthings app see the device and reports the status fine.  I just can't control the switch.  I did not install any smartapps for the device, it didn't seem like I would need to.  I am new to this world so I don't know what I could be missing.

**Comment by workingmonk** [comment]
are you sure the device handler that you copied over is correctly controlling the switch? please reach out to support or community.smartthings.com for more debugging. we kinda use the issues page to track problems with the official device handlers
