### ISSUE TITLE
Aeon Multisensor (Gen 6) throwing.

### ISSUE THREAD

**Issue by jasisk** [SmartThingsCommunity/SmartThingsPublic#222]
`java.lang.SecurityException: Getting properties on class physicalgraph.device.Device_$$_javassist_11 is not allowed @` [line 246](https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/1965f105843c5519fe85dfcc3c6676b288c4cad1/devicetypes/smartthings/aeon-multisensor-6.src/aeon-multisensor-6.groovy#L246)

This happens when attempting a secure inclusion on battery or wired.

**Comment by workingmonk** [comment]
@mckeed

**Comment by mckeed** [comment]
This is fixed in https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/209

I'll try to get that reviewed today.
