### ISSUE TITLE
Multiple Stock Handlers Not Updated to multiAttributeTiles?

### ISSUE THREAD

**Issue by vseven** [SmartThingsCommunity/SmartThingsPublic#2324]
Just a general note.  Many of the "stock" handlers written by SmartThings do not take advantage of the multiAttributeTile and I believe they should to maintain consistency across the device handlers.  Updating the code should be a couple minutes per handler and would greatly improve the look and feel in the app.

For example the stock "Z-Wave Door/Window Sensor" at https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/zwave-door-window-sensor.src/zwave-door-window-sensor.groovy uses standardTiles.  I have put in a pull request and the only thing I have changed is switching it to a multiAttributeTile.  

I am willing to do the others myself if I know the pulls will be committed but I don't want to waste my time if they will be ignored.  I also don't want to use a custom handler as then it runs in the cloud instead of locally and I'd like to maintain local control when at all possible.

**Comment by workingmonk** [comment]
@vseven i've merged your PR and it should be in QA this week for the prod release next week. If you already have the PR ready for the simple change to multi attribute tiles, open the PR and tag me

**Comment by vseven** [comment]
Awsome.  Ill go through the other ones that i know havent been updated, do a PR, and tag you.  Thanks!

**Comment by workingmonk** [comment]
@vseven Awesome job on all the PRs. I've added the ticket number to all your PRs so that they are tracked and go into production next Tuesday. 

Thanks again 😄

**Comment by vseven** [comment]
No problem.  Think i got the majority of them, at least the easy ones.  If i find any others I'll update them.

Oh....do me a favor and ask someone why the generic "Z-Wave Water Valve" doesn't run locally.  Its one of my only devices that doesn't and i would think it should.

**Comment by vseven** [comment]
@workingmonk  - Last of them updated.  Couple that looked to be depreciated/not used/test devices I didn't touch but anything that looked current should be updated now so I think I'm done.

Really hope to see the newer EcoBee thermostat device soon....the current one looks "old" for lack of a better term.

**Comment by workingmonk** [comment]
z-wave water valve local question: i know the team is looking into a date in the future when more devices will be added to run locally. for now it is was the change in local architecture to keep parity with the old one

for Ecobee, tag `marstorp` on the PR again if you don't hear back. he is trying out that tile change and has more suggestions for you.
