### ISSUE TITLE
Nest Thermostat Temp Value and Forecasted Temp Value

### ISSUE THREAD

**Issue by jeffjaslow** [SmartThingsCommunity/SmartThingsPublic#2344]
I have a Nest Thermostat and live out in Colorado where there are some major temperature fluctuations: 30 degree nights and 80 degree days...But, sometimes 30 degree nights turn into 48 degree days...If I set the Nest Temp to 60 when the Outside temperature reaches let's say 68 then the house over the course of the day goes into the 80s...If I set it lower like Outside Temp to 50 then if the Outside Temp never gets past 58 then the house remains too cold at the 60 Nest temp set.

I need the Nest Thermostat to find a Forecasted Temp Value and to adjust the Thermostat Temp Value at a specified Time Value.
I am not a programmer so I was wondering if there was a way to tweak your program to do that?

Any help would be appreciated.

Thanks.

Jeff Jaslow

**Comment by workingmonk** [comment]
@jeffjaslow as of today, the nest thermostat is not officially supported. If you got the code from our awesome community, this could be a great recommendation for their integration.
