### ISSUE TITLE
Multiple CentraLite / SmartThing DTH's Showing 100% Battery Incorrectly Still

### ISSUE THREAD

**Issue by vseven** [SmartThingsCommunity/SmartThingsPublic#2428]
This has been a ongoing problem for multiple people, myself included.  The issue appears to be related to firmware updates but no DTH update from my understanding.  There is a existing support ticket 412456 on it and some forum posts (https://community.smartthings.com/t/st-multi-sensor-battery-reporting-issues/98924).  Another community member also issued a update to one of the DTH that seemed to fix the issue (https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/2405) but no comments have been made on it.

Is this issue being worked on to fix the DTH's so they don't constantly show 100%?  I have had sensors die (dead batteries) while showing 100% and never changing due to this bug.  If it's being worked on is there a ETA?  If not can we get PR 2405 looked at and committed (as a example....others need to be done also)?

**Comment by vseven** [comment]
It's now been two months and my SmartSense leak sensors still all show 100% battery due to the same bug introduced in apparently pull requests 2158 and 2196.

Since the forum post about this is being ignored I'll ask here.    @posborne @varzac @tpmanley   - When will this be fixed?

**Comment by workingmonk** [comment]
there are 2 fixes coming soon:
1. short term fix: this will revert the reporting to the old style. This isn't the most accurate but should at least make sure that older firmware sensors can report numbers other than 100% before they die

2. long term fix: we are doing more testing for the past few weeks to get the correct battery characteristic mapped to the zigbee battery reporting limitation so that we can have a better experience for our users

**Comment by vseven** [comment]
It would be nice to get a status update instead of complete silence over the last two months as it's getting extremely frustrating.  I had another sensor go offline and we had bad storms here last week with flooding in areas.  The whole reason I bought these is because they run "locally" and I can be alerted if there is water not only under my sinks but in my basement and at the basement drain.  But if they don't work then it doesn't matter much.  

Thank-you for finally responding.  Maybe when people email support they can tell them what you did instead of telling everyone "We know about it, make sure to just keep changing your batteries".

**Comment by dm7500** [comment]
Not sure if this helps, but I'm still seeing this issue with Samsung branded multi-sensors/motion sensors. I've had them installed for months now, and all 3 still read 100%. No issues with them yet thankfully, but I'm nervous about them dying at a very inconvenient time. Is there an upgraded DTH I can use for these in the meantime?
