### ISSUE TITLE
Smart Light: motion triggered lights

### ISSUE THREAD

**Issue by sbdobrescu** [SmartThingsCommunity/SmartThingsPublic#255]
Smart Lighting app doesn't handle motion triggers correctly. Active motion doesn't cancel the timer to turn off the light.

**Comment by bridaus** [comment]
I see this issue as well.

**Comment by tylerlange** [comment]
This issue is unrelated to the code hosted on this repo. I'm closing this issue.

Please make sure you've contacted support@smartthings.com so that your issue is reported to the correct channel.

Thanks,
Tyler
