### ISSUE TITLE
Routines execute partially

### ISSUE THREAD

**Issue by sbdobrescu** [SmartThingsCommunity/SmartThingsPublic#256]
Some routines don't fully execute. Example, Good Night routine didn't set heating/cooling points on Honeywell thermostat nor turned off Wemo switches.

**Comment by tylerlange** [comment]
This issue is unrelated to the code hosted on this repo. I'm closing this issue.

Please make sure you've contacted support@smartthings.com so that your issue is reported to the correct channel.

Thanks,
Tyler
