### ISSUE TITLE
Smart Lightning dim level

### ISSUE THREAD

**Issue by sbdobrescu** [SmartThingsCommunity/SmartThingsPublic#257]
Set dim level doesn't work for some switches. E.G - dimmer switch model 12724.

**Comment by bridaus** [comment]
It also doesn't work for my new DragonTech Switch # WS100

**Comment by tylerlange** [comment]
This issue is unrelated to the code hosted on this repo (Smart Lighting is not hosted here). I'm closing this issue.

Please make sure you've contacted support@smartthings.com so that your issue is reported to the correct channel.

Thanks,
Tyler
