### ISSUE TITLE
(iOS 2.0.4) Correct mode is not reflected in iOS app after a mode change.

### ISSUE THREAD

**Issue by ronsarkar** [SmartThingsCommunity/SmartThingsPublic#259]
Mode change happens but correct mode is not reflected in the app. It shows the stale mode unless the app is killed and restarted.

How to reproduce:

GoodMorning! routine triggers when things start happening in the morning, Mode changes from Night to Home. The iOS app still shows the stale mode.

**Comment by tylerlange** [comment]
This issue is unrelated to the code hosted on this repo (iOS app is not hosted here). I'm closing this issue.

Please make sure you've contacted support@smartthings.com so that your issue is reported to the correct channel.

Thanks,
Tyler
