### ISSUE TITLE
(iOS 2.0.4) Icons are missing from installed SmartApps.

### ISSUE THREAD

**Issue by ronsarkar** [SmartThingsCommunity/SmartThingsPublic#260]
Icons have disappeared for most of the installed SmartApps from the mobile app including the Smart Lighting.

**Comment by tylerlange** [comment]
This issue is unrelated to the code hosted on this repo. I'm closing this issue.

Please make sure you've contacted support@smartthings.com so that your issue is reported to the correct channel.

Thanks,
Tyler
