### ISSUE TITLE
 java.lang.SecurityException In zwave-lock.groovy

### ISSUE THREAD

**Issue by pcartwright81** [SmartThingsCommunity/SmartThingsPublic#275]
In zwave-lock.groovy
state.keySet().findAll  Line 555
 java.lang.SecurityException: Invoking methods on class java.util.Collections$SynchronizedSet is not allowed: findAll @ line 555

**Comment by workingmonk** [comment]
@mckeed Do we need to update the DTH for locks or the platform?

**Comment by mckeed** [comment]
Both I think. See DVCSMP-1265 and CLOUD-545

**Comment by mckeed** [comment]
See PR https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/297
