### ISSUE TITLE
zll-rgbw-bulb.groovy no longer controls colour temperature correctly for OSRAM LIGHTIFY LED Classic A60 RGBW

### ISSUE THREAD

**Issue by mikemoate** [SmartThingsCommunity/SmartThingsPublic#2771]
The changes in #2729 prevent the colour temperature control from working correctly with the OSRAM LIGHTIFY LED Classic A60 RGBW.

Creating a device type handler using the code before this PR was merged (i.e. https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/4e03718c8891666095e2e58c5e54c6e256348641/devicetypes/smartthings/zll-rgbw-bulb.src/zll-rgbw-bulb.groovy) and then using this for these devices, allows the colour temperature control to work correctly.

**Comment by workingmonk** [comment]
@mikemoate What exactly are you seeing as an issue? 

cc @greens @tpmanley

**Comment by workingmonk** [comment]
@mikemoate found the issue. fix coming soon

**Comment by workingmonk** [comment]
https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/2772

**Comment by workingmonk** [comment]
@mikemoate the fix has been deployed. Please close the issue once you confirm it on your end

**Comment by mikemoate** [comment]
@workingmonk Many thanks for the swift turnaround. I updated my custom device type handler to the latest code, and the colour temperature control now works correctly. When will this be released for the built-in/provided device type handler (so I can move off the custom handler) ?

**Comment by workingmonk** [comment]
@mikemoate what do you mean by built-in? I deployed the fix yesterday to production
