### ISSUE TITLE
EcoBee Remote Sensor displaying Motion on overview in new app instead of Temperature

### ISSUE THREAD

**Issue by vseven** [SmartThingsCommunity/SmartThingsPublic#3614]
https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/8991cd9afcd383c6b9c6ca72db716e65278d592e/devicetypes/smartthings/ecobee-sensor.src/ecobee-sensor.groovy#L19

Not sure if this is being caused by lack of meta data (assuming) but in the new Connect app EcoBee sensors are showing motion as the primary value in the overview list while in the Classic app they show temperature.  Should be consistent with Classic and display temperature.

**Comment by tpmanley** [comment]
@workingmonk FYI

**Comment by workingmonk** [comment]
we've got a few more changes lined up for C2C. that should handle this bug

**Comment by vseven** [comment]
Sounds like this is being fixed, closing the issue.

**Comment by vseven** [comment]
So a recent update (within the last month) flipped this back and these are again defaulting to motion in STSC while still, correctly, showing temperature in Classic.

**Comment by workingmonk** [comment]
@vseven not sure what caused it to flip in the first place (possibly related to the UI overhaul), but we made the changes today to fix it back to show temperature again in the device list view.

**Comment by vseven** [comment]
Also as a side note the "graph" that you can click on only shows the temperatures in Celsius instead of Fahrenheit even though the region/sensor shows the temperature in Fahrenheit. Maybe this can be looked at or fixed at the same time:

![EcoBeeRemoteSensor](https://user-images.githubusercontent.com/999179/54880862-23ea7a00-4e20-11e9-9dc4-f31e13a16942.jpg)

**Comment by workingmonk** [comment]
@vseven that is a separate issue controlled by the UI plugin. I have filed a ticket with the plugin team to get that fixed.
