### ISSUE TITLE
SmartSense Temperature/Humidity sensors not displaying value on overview in Connect app

### ISSUE THREAD

**Issue by vseven** [SmartThingsCommunity/SmartThingsPublic#3615]
https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/8991cd9afcd383c6b9c6ca72db716e65278d592e/devicetypes/smartthings/smartsense-temp-humidity-sensor.src/smartsense-temp-humidity-sensor.groovy#L19

On the overview screens in the new Connect app these sensors just show a single dash.  When you view their details they show "Connected" as the primary tile then the correct info of humidity, temperature, and battery below that.  In Classic they show temperature on the overview and temperature as the primary tile.

This DTH should be changed to match how Classic displays, temperature on overview and as primary tile, with remaining info below.

**Comment by tpmanley** [comment]
Thanks @vseven , the fix for this is already in the works
