### ISSUE TITLE
Bug In helper function colorUtil.hsvToHex

### ISSUE THREAD

**Issue by vseven** [SmartThingsCommunity/SmartThingsPublic#3625]
There seems to be a bug in this function.  From what I can tell if Hue is passed in as a 0 it doesn't know what to do and returns last value.  For example using Alexa to change a RGB bulb in this order give these results:

"Green" passed from Alexa:  hue:33, saturation:100
Result of function = color: #05FF00   (correct)

"Blue" passed from Alexa:  hue:67, saturation:100
Result of function = color: #0500FF   (correct)

"Red" passed from Alexa:  hue:0, saturation:100
Result of function = color: #0500FF   (incorrect, same as last call of blue)

Then just to test if it really is throwing up last value I call Green again and get #05FF00.  I then call Red and get  #05FF00 again.

I've fixed this issue in the past but I have no access to that helper function so hopefully you guys can track it down.  Tagging @tpmanley as looking through searches on hue issues his name comes up a lot.  This is affecting a good number of DTH's that have been converted to use this helper, I personally have been working on Aeon LED Bulb and RGBW Light and both are affected.  Manually setting red via the color wheel of course works fine (since no conversion is going on).

**Comment by dkirker** [comment]
@vseven I dug around to check out the issue. The code for hsvToHex does return the right value for hue:0 saturation:100. When you said "returns last value" this threw up a flag. I noticed you have this line at https://github.com/vseven/SmartThings_VSeven/blob/master/devicetypes/vseven/zwave-rgbw-bulb.src/zwave-rgbw-bulb.groovy#L192

`def hue = value.hue ?: device.currentValue("hue")`

Unfortunately, Groovy will see value.hue=0 as a failure of this condition and you will get hue=device.currentValue("hue") -- which would explain why if you call for a color with any hue value and a saturation of 100, then call for red, you will see the color you last called for. (The same for a similar line for saturation.)

**Comment by vseven** [comment]
@dkirker - So my code is 95% copied from "aeon-rgbw-bulb" which it seems has this bug:

https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/10a440d468f5e9c79f8cc1630ff621adbef3556e/devicetypes/smartthings/aeon-led-bulb.src/aeon-led-bulb.groovy#L178

Same bug exists in "rgbw-light":

https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/10a440d468f5e9c79f8cc1630ff621adbef3556e/devicetypes/smartthings/rgbw-light.src/rgbw-light.groovy#L237

And in "aeon-rgbw-bulb-6":

https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/10a440d468f5e9c79f8cc1630ff621adbef3556e/devicetypes/smartthings/aeon-led-bulb-6.src/aeon-led-bulb-6.groovy#L252

What would be the fix?  Also the next line in both is:

`def saturation = value.saturation ?: device.currentValue("saturation")`

would also fail as you said on a call for grey (Hue of 100, saturation of 0) and needs the same fix.

**Comment by vseven** [comment]
@dkirker - Now I'm confused why you are even making this check.  All three SmartThings DTH's are identical and say:

```
def hue = value.hue ?: device.currentValue("hue")
def saturation = value.saturation ?: device.currentValue("saturation")
if(hue == null) hue = 13
if(saturation == null) saturation = 13
def rgb = huesatToRGB(hue, saturation)
result << zwave.switchColorV3.switchColorSet(red: rgb[0], green: rgb[1], blue: rgb[2], warmWhite:0, coldWhite:0)
```
Why even bother re-sending the old values?  I ask because I assume the helper function has some checks of its own and will return nothing if hue and/or saturation aren't what it wants, I mean I would hope it has a minimum maximum function to make sure hue and sat are between 0 and 100.  For example I changed the code in my DTH to just this for testing:
```
def rgb = huesatToRGB(value.hue, value.saturation)
result << zwave.switchColorV3.switchColorSet(red: rgb[0], green: rgb[1], blue: rgb[2], warmWhite:0, coldWhite:0)
```
And it now works fine for all colors including red and grey.  Is there a better way to go about this?

**Comment by tpmanley** [comment]
I'm not sure why the code was written that way - it's been that way since we put it in GitHub. I've filed an internal ticket to get this fixed up in those DTHs you mentioned. I haven't looked super closely but your change does seem reasonable.

**Comment by vseven** [comment]
Tom - can you confirm that Hue and saturation are checked to make sure they are available between 0 and 100 and if they are not they are brought up to those using a minimum and maximum statement within colorUtil.hsvToHex?  If so I think my suggestion should work and looks a lot cleaner. The other option would be to do the minimum and maximum before sending it to the helper function but why have to do that repeatedly in multiple DTHs if it's covered in there.

**Comment by tpmanley** [comment]
Here is the code. It will throw an exception if the input values are not between 0 and 100 which is the valid range for hue/sat in the Color Control capability.
```
private static final hueSatRange = (0..100)
static String hsvToHex(hue, saturation, value = 100){
		if (!hueSatRange.contains(hue) || !hueSatRange.contains(saturation) || !hueSatRange.contains(value)) {
			throw new IllegalArgumentException("All Values must be Integers between ${hueSatRange[0]} and ${hueSatRange[-1]}. Received: (${hue}, ${saturation}, ${value})")
		}

		def r, g, b
		def h = hue / 100
		def s = saturation / 100
		def v = value / 100

		def i = Math.floor(h * 6)
		def f = h * 6 - i
		def p = v * (1 - s)
		def q = v * (1 - f * s)
		def t = v * (1 - (1 - f) * s)

		switch (i % 6) {
			case 0:
				r = v
				g = t
				b = p
				break
			case 1:
				r = q
				g = v
				b = p
				break
			case 2:
				r = p
				g = v
				b = t
				break
			case 3:
				r = p
				g = q
				b = v
				break
			case 4:
				r = t
				g = p
				b = v
				break
			case 5:
				r = v
				g = p
				b = q
				break
		}

		// Converting float components to int components.
		def r1 = String.format("%02X", (int) (r * 255.0f))
		def g1 = String.format("%02X", (int) (g * 255.0f))
		def b1 = String.format("%02X", (int) (b * 255.0f))

		return "#$r1$g1$b1"
	}
```

**Comment by vseven** [comment]
So one would assume that hue and saturation should never be anything other than 0 to 100. And since it seems the Color Picker is passing over hex but online services such as Amazon and Google are passing over hue and saturation one would also assume that they are doing so correctly.

With that said would you guys rather that function throw an error and people add a Min and Max to the dth as needed or would you guys rather modify the function to do the min and max? 

Also talking to @greens it sounds like rgbw-light is kinda old (re: https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/3599#issuecomment-433031659).  I'm going to put in a pull request for a new "Z-Wave RGBW Bulb" and a "Z-Wave RGBW Controller" that should obsolete rgbw-light.  "bulb" will match the Aeon except bring it up to date and "controller" will replace the white color temperature with white level since most RGBW controllers dont do temperature and just dimmer the white channel.  I just wanted this bug fixed before submitting so let me know if I should do the min/max on the DTH side as a just in case.

**Comment by dkirker** [comment]
I suspect the way it was done in the existing device handlers was a hack around either: 1. A lack of strict, contract based capabilities, or 2. Some undocumented reason to hack around either deficiencies in the device or our platform at the time it was added, or 3. The "previous value" was used as a filler for a default and the Groovy spec treated null, undefined, and zero differently. (I haven't followed the changes in the spec, so that is... well... "spec"ulation. ;) )

As for how to go forward with this... @tpmanley assigned the internal ticket to me, so I'll go ahead and read up on everything and see what can be done. At the very least, the existing code can be fixed so that this doesn't come back up.

**Comment by vseven** [comment]
So thinking about this I _would_ want the helper app to throw the error if it gets a bad value so doing a min/max check doesn't make sense as you'd only be masking a possible issue.  Same with null, I would rather pass a null and have the hsvToHex function throw a error for the same reason.  With that said my code, I think, makes the most sense.

I'm going to enter a new DTH today based on this code and add my changes.  You and @greens can review it and hopefully what I'm requesting makes sense and will be a improvement over the existing DTH's (aeon0-rgbw-bulb and rgbw-light).
