### ISSUE TITLE
Which license is the ecobee-connect.groovy file under?

### ISSUE THREAD

**Issue by StrykerSKS** [SmartThingsCommunity/SmartThingsPublic#368]
There is an ongoing discussion/debate regarding some derivative works based on the ecobee-connect smartapp. It would be very helpful to understand what license the file is distributed under.

// StrykerSKS

**Comment by snakedog116** [comment]
I think it should be Apache, that's what it was to start, and then it was deleted (I believe in error) 1b9d2fe @kwarodom

I've submitted a pull request to put this back.

From what I understand, the original code was under Apache, so the resulting code should be too.

Can someone from SmartThings please confirm this?

Thanks

**Comment by kwarodom** [comment]
@snakedog116 and @StrykerSKS The ecobee-connect smartapp is under Apache license. It was mistakenly deleted from the original service manager. Thanks for bringing up the issue. I will correct it accordingly.

**Comment by snakedog116** [comment]
Pull has been committed, this is fixed. @StrykerSKS , I think you need to close this issue?
