### ISSUE TITLE
Ecobee Device - Celsius

### ISSUE THREAD

**Issue by snakedog116** [SmartThingsCommunity/SmartThingsPublic#377]
I've installed the Ecobee device for my Ecobee3. I live in Canada and my Ecobee is set to Celsius.

The ecobee device reads this correctly and displays the correct temperature (20 Celsius). However when I adjust the temperatures it pushes the new set points in Fahrenheit:
So for example, the house is 20, the app says 20 it's all good. The up arrow moves it to 21, but now the thermostat is set to 21 fahrenheit! Which is way too cold!

Also, the remote sensors are all translating everything to fahrenheit, so it knows my sensors are about 67, 68 etc. It would be nice to display this in Celsius for us that use the metric system.

Any developers know how to fix this?

**Comment by tylerlange** [comment]
We have an issue opened internally to fix temperature reports on Ecobee. We're aiming for a release in January. I'm closing this issue out in the mean time.
