### ISSUE TITLE
Temperature reporting is broken 

### ISSUE THREAD

**Issue by GSzabados** [SmartThingsCommunity/SmartThingsPublic#38801]
@greens, @dkirker, @tpmanley 

Please see the topic on the community forum:

https://community.smartthings.com/t/old-smartthings-multi-sensor-stopped-updating-2-3-weeks-ago-broken-standard-device-handler/200651

Log:

2de678XXX 12:34:48 PM: error java.lang.NumberFormatException: For input string: “40.1” @line 318 (getTempResult)
2de678XXX 12:32:17 PM: error java.lang.NumberFormatException: For input string: “39.6” @line 318 (getTempResult)
2de678XXX 12:29:48 PM: error java.lang.NumberFormatException: For input string: “39.2” @line 318 (getTempResult)

Effected DH:

https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/smartsense-multi.src/smartsense-multi.groovy

**Comment by tpmanley** [comment]
This was fixed in https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/38946. Thank you for the bug report.
