### ISSUE TITLE
Issues with zen-thermostat.groovy 

### ISSUE THREAD

**Issue by pcartwright81** [SmartThingsCommunity/SmartThingsPublic#408]
When the thermostat is in Fahrenheit mode the temperatures show decimals such as 72.7.

I have errors in my error log that show up as 
read attr - raw: 93670102010A2900190D00, dni: 9367, endpoint: 01, cluster: 0201, size: 0A, attrId: 0029, encoding: 19, value: 000d

Pretty sure that the alpha characters are lowercase when coming from the thermostat.

Also the below method is missing 000c which is heating

I believe 000c and 000d to be stage 2 heat, but no one has the API for this thermostat.  I contacted Smartthings, ZEN, and openhome.io and this was not helpful.  I am coming from a Radio Thermostat and they distinguish when your thermostat is in aux mode.

def getOperatingStateMap() { [
    "0000":"idle",
    "0001":"heating",
    "0002":"cooling",
    "0004":"fan only",
    "0005":"heating",
    "0006":"cooling",
    "0008":"heating",
    "0009":"heating",
    "000A":"heating",
    "000D":"heating",
    "0010":"cooling",
    "0012":"cooling",
    "0014":"cooling",
    "0015":"cooling"
]}

**Comment by tylerlange** [comment]
@dkirker

**Comment by pcartwright81** [comment]
I also figured out by viewing the logs that 05 is emergency heat, and 01 is Auto
My mode map is like this.  However auto mode has to be enabled in advanced settings
def getModeMap() { [
    "00":"off",
        "01":"auto",
    "03":"cool",
    "04":"heat",
        "05":"emer"
    ]
}

**Comment by StrykerSKS** [comment]
"emer" is not a valid mode value per the capability, shouldn't it be "emergency heat"?

**Comment by cehoffman** [comment]
I recently got a Zen Thermostat (today) and have already noted the above failings in the default device handler. I've begun modifying it to fix those issues and at least report auto mode and allow you to switch into auto mode. However I'm stuck at trying to get the setpoint value used when in auto mode. Does anyone know where to get the engineering document for the zigbee messages used with the zen thermostat? Is there anything like the zwave alliance for zigbee that has the configuration and other details of zigbee devices?

**Comment by workingmonk** [comment]
@cehoffman still stuck on a zigbee document?
