### ISSUE TITLE
Integration with 2Gig CT100 humidity

### ISSUE THREAD

**Issue by magickarle** [SmartThingsCommunity/SmartThingsPublic#700]
@bflorian 

Greetings.
I have installed the app and was able to choose the "monitor the humidity of" the thermostat

I do not have a smart outlet yet but have Aeon microcontroller light switch.
I was able to choose it as the "control humidity"

I have set the "when the humidity rises above" to 0
I have set the "when the humidity drops below" to 50

The light switch is not triggered.
Thanks for directing me in the right direction.

**Comment by workingmonk** [comment]
closing this as it is not an issue.
