### ISSUE TITLE
Ecobee Connect Smartapp

### ISSUE THREAD

**Issue by pcartwright81** [SmartThingsCommunity/SmartThingsPublic#864]
I am receiving an error when adding my ecobee 3 thermostat from Marketplace=>things=>climate control=>thermostats=>ecobee+>ecobee 3
The error is as follows

error groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method physicalgraph.event.EventService#create.
Cannot resolve which method to invoke for [null, class java.util.LinkedHashMap] due to overlapping prototypes between:
[class physicalgraph.app.InstalledSmartApp, interface java.util.Map]
[class physicalgraph.device.cache.HubDTO, interface java.util.Map]
[class physicalgraph.device.cache.InstalledSmartAppDTO, interface java.util.Map]
[class physicalgraph.device.cache.LocationDTO, interface java.util.Map]
[class physicalgraph.location.Location, interface java.util.Map] @ line 318

Is this an error in the smartapp or my hub?

**Comment by jasonbio** [comment]
This shouldn't be an issue anymore - try connecting again. (Check your installed SmartApps first and make sure there isn't already an Ecobee Connect listing - if there is, remove it before trying again)

**Comment by pcartwright81** [comment]
Happy to report that this is now working.  Thank you.
